// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAF3dRx0gQ8N-nnH4I7HEGiSs5L0bc6jg',
    appId: '1:215554073421:android:b38c2d4e655d8be5fc4d04',
    messagingSenderId: '215554073421',
    projectId: 'tarefas-app-exemplo',
    databaseURL: 'https://tarefas-app-exemplo.firebaseio.com',
    storageBucket: 'tarefas-app-exemplo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5j4YuNqsQNChO8CesJFXCilHl-n18F4M',
    appId: '1:215554073421:ios:6c2fff17ce02ebeffc4d04',
    messagingSenderId: '215554073421',
    projectId: 'tarefas-app-exemplo',
    databaseURL: 'https://tarefas-app-exemplo.firebaseio.com',
    storageBucket: 'tarefas-app-exemplo.appspot.com',
    androidClientId: '215554073421-9kao8cenrvskfjijtunu3bg520un4t2b.apps.googleusercontent.com',
    iosClientId: '215554073421-iddese2hpg6c2rerta1lagv8ps201lgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentCalendarApp',
  );
}
